services:
  - type: web
    name: openai-flask-demo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
